# netlify.toml — MINIMAL SPA + cache
[build]
  command = "npm run build"
  publish = "dist"

# SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Cache sûr par défaut pour HTML
[[headers]]
  for = "/*"
  [headers.values]
  Cache-Control = "public, max-age=0, must-revalidate"

# Cache long pour les assets fingerprintés Vite
[[headers]]
  for = "/assets/*"
  [headers.values]
  Cache-Control = "public, max-age=31536000, immutable"

