-- Vérifié le 2026-07-12 (audit gabarits d'empreinte) : patient_biometrics
-- avait déjà RLS activé, avec 3 policies existantes correctement scopées
-- par clinique (pb_select_same_clinic, pb_insert_same_clinic,
-- pb_update_same_clinic — toutes basées sur
-- clinic_staff.id = auth.uid() AND clinic_staff.clinic_id = patient_biometrics.clinic_id).
-- Cette instruction est donc un no-op sur l'état actuel ; elle reste ici en
-- garde-fou pour que ce fichier documente et réaffirme l'exigence si RLS
-- était un jour désactivé par erreur sur cette table.
--
-- Les deux seuls points d'accès applicatifs (service role, donc indifférents
-- à RLS) sont netlify/functions/biometrics-candidates.ts et
-- biometrics-enroll.ts, protégés par APP_INGEST_SECRET. L'accès navigateur
-- (clé anon publique) passe par ces policies clinic-scoped.
alter table patient_biometrics enable row level security;
